@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package novarch.jojomod.entities.stands.attacks;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;