@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package novarch.jojomod.entities.stands;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;